### ISSUE TITLE
Add a Kafka Broker - turn `/fetch` into a Kafka producer & turn `/manipulate` into a  horizontally auto-scalable Kafka consumer

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/tinyhats#72]
<img width="768" alt="Screen Shot 2021-10-17 at 4 18 48 PM" src="https://user-images.githubusercontent.com/10321085/137643521-125c7ba8-d3af-4944-90f3-0735b874a260.png">

We need to add Kafka functionality to the application. To do this successfully, we need to add modifications

### Pre-reqs
- [x] We need to make sure that each message for the Kafka Broker does not exceed 1MB. Therefore, the Kafka message CANNOT contain the bare base64 image. We need to change the code so with the image name or ID we can fetch the base64 data from the MySQL database for `/manipulate` and `/fetch`

### Work
- [ ] Spin up Kafka broker namespace using [Strimzi](https://strimzi.io/docs/operators/latest/quickstart.html#proc-product-downloads-str).  
- [ ] Turn `/fetch` microservice into a Kafka producer, writing to the Kafka broker instead of sending a REST call
- [ ] Turn `/manipulate` microservice into a Kafka consumer, reading from the Kafka broker instead of receiving a REST call
- [ ] Enable Horizontal Autoscaling for `/manipulate` using this [walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)

**Comment by emsesc** [comment]
Have `/manipulate` use the received image ID and make a request to the MySQL DB to get the base64
